### ISSUE TITLE
random question­ 

### ISSUE THREAD

**Issue by leahcimto** [JeffaloBob/JeffaloBob#1]
sorry if this is the wrong place to put this but I'm wondering if there is a way to search the dustbin or all forums including the dustbin @jeffalo

**Comment by cobaltt7** [comment]
No, you can not search the dustbin AFAIK.

You can try asking DatOneLefty on Scratch if he has any plans to implement this into ScratchDB (the inner workings of Ocular).
________________________________
From: leahcimto ***@***.***>
Sent: Sunday, April 18, 2021 12:29:29 PM
To: jeffalo/jeffalo ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [jeffalo/jeffalo] ­ (#1)


sorry if this is the wrong place to put this but I'm wondering if there is a way to search the dustbin or all forums including the dustbin @jeffalo<https://github.com/jeffalo>

**Comment by jeffalo** [comment]
sorry for the late response, but there is no way that i'm aware of.
